### ISSUE TITLE
CIW format does not support importing/exporting notes

### ISSUE THREAD

**Issue by hammady** [rayyansys/rayyan-formats-plugins#32]
Add proper support for notes.

**Comment by kohrVid** [comment]
Unfortunately I'm struggling to find an example of a notes tag in a `.ciw` file. The tags used in `.ris` files seem quite similar and they use the `N1` tag in this case - should `.ciw` files do the same?

**Comment by hammady** [comment]
Check official docs for the format (Web of Science)

**Comment by kohrVid** [comment]
> Check official docs for the format (Web of Science)

After quite a lot of digging, the closest thing to official documentation that I've been able to find is [this list of tags for the Web of Science format](https://images.webofknowledge.com/WOKRS534DR1/help/WOS/hs_wos_fieldtags.html). Unfortunately, I can't see anything in that list that looks like a "notes" field. Should the tag perhaps have a more specific name that is in this list? If not, is there a chance that the format doesn't actually support this tag?

**Comment by hammady** [comment]
@kohrVid Yes, could be that the format does not support notes.
