### ISSUE TITLE
Import failure due to runtime errors parsing dates

### ISSUE THREAD

**Issue by hammady** [rayyansys/rayyan-formats-plugins#46]
When you try to import a deduplicated search from EndNote to Rayyan, the import fails. 

Customer says: I have tried the xml, txt and csv formats, but some error or other keeps coming up. Either "Wrong number of arguments (5, expecting 1-3)" or the most common one is "Undefined method 'sub'..".

Some references have the date like this:
%8 Sep 2011
2022-04-27
More failing examples are available upon request.

This will throw the following error:
Error: wrong number of arguments (given 5, expected 1..3)

**Comment by kohrVid** [comment]
As discussed last week, the user's import seems to have run into a [known issue in the ref_parser repo](https://github.com/rayyansys/ref_parsers/issues/9). Whilst I think addressing the parsing issue would take a long time, I do wonder if it's worth handling the unusual date formats that were found in the meantime. I've raised a PR just in case
