### ISSUE TITLE
Proper importing and exporting of DOIs (all formats)

### ISSUE THREAD

**Issue by mouradvt04** [rayyansys/rayyan-formats-plugins#9]
If the uploaded file has the DOI we need to properly parse it and export it.
This applies to all formats.

**Comment by mouradvt04** [comment]
There is also one suggestion (https://rayyan.uservoice.com/admin/tickets/1253) to parse more fields such as name of database, database provider, keywords, and date field.

**Comment by kohrVid** [comment]
I'm in the process of writing a PR that will add DOI to the following formats:
- BibTex
- CIW
- EndNote
- Refman

Most of the other formats didn't seem to support field tags as far as I could tell and the [Medline plugin already already supports DOI tags](https://github.com/rayyansys/rayyan-formats-plugins/commit/f757b7340896b32a50c74a49aa178e45b2355478). Is that ok or is there anything that I've missed out?
